apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-deployment
  labels:
    app: simple-node
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      containers:
      - name: simple-node-app
        image: athukral1/simple-node-app
        ports:
        - containerPort: 3000
